[config]
model = "bedrock/anthropic.claude-3-sonnet-20240229-v1:0"
model_turbo = "bedrock/anthropic.claude-3-sonnet-20240229-v1:0"
fallback_models = ["bedrock/anthropic.claude-3-haiku-20240307-v1:0"]

[pr_reviewer]
extra_instructions = "answer in Japanese"

[pr_description]
extra_instructions = "answer in Japanese"

[pr_questions]
extra_instructions = "answer in Japanese"

[pr_code_suggestions]
extra_instructions = "answer in Japanese"

[pr_update_changelog]
extra_instructions = "answer in Japanese"
